name: Check URLs

on:
  workflow_dispatch: # Manually run workflow.
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday.

jobs:
  check_urls:
    runs-on: ubuntu-latest
    # Do not run this job on forks, as it's not cool to query servers for nothing.
    if: ${{ github.repository == 'endoflife-date/endoflife.date' }}
    steps:
      - name: Checkout site
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

      - name: Setup ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Perform URLs check
        run: bundle exec jekyll build
        env:
          MUST_CHECK_URLS: true
